#' Plot protein numbers
#'
#' \code{plot_numbers} generates a barplot
#' of the number of identified proteins per sample.
#'
#' @param se SummarizedExperiment,
#' Data object for which to plot protein numbers
#' (output from \code{\link{make_SILAC_se_parse}()}).
#' @param plot Logical(1),
#' If \code{TRUE} (default) the barplot is produced.
#' Otherwise (if \code{FALSE}), the data which the
#' barplot is based on are returned.
#' @return Barplot of the number of identified proteins per sample
#' (generated by \code{\link[ggplot2]{ggplot}})
#' @examples
#' if(interactive()){
#' # Load example
#' data <- doxTreatment
#' data <- data[data$Reverse != "+" & data$Potential.contaminant != "+" &
#' data$Reverse != "+" ,]
#' data_unique <- make_unique(data, "Gene.names", "Protein.IDs", delim = ";")
#' # Make SummarizedExperiment
#' ratios<-"ratios"
#' columns_positions<-grep(ratios, colnames(proteins_unique))
#' se <- make_SILAC_se_parse(data_unique, columns_positions,
#' invert= "ligth", numerator= "RBP",denominator= "Organic", conditions=2,
#' bioreplicates=3,chars = 0)
#' plot_numbers(se) #uses theme_RBP
#' }
#' @import ggplot2
#' @import dplyr
#' @importFrom dplyr group_by
#' @importFrom dplyr mutate
#' @importFrom tibble rownames_to_column
#' @importFrom dplyr left_join
#' @importFrom tidyr pivot_longer
#' @import glue
#' @export
plot_numbers <- function(se, plot = TRUE) {
  # Show error if input is not the required classes
  assertthat::assert_that(inherits(se, "SummarizedExperiment"),
                          is.logical(plot),
                          length(plot) == 1)
  
  # Make a binary long data.frame (1 = valid value, 0 = missing value)
  df <- assay(se) %>%
    data.frame() %>%
    tibble::rownames_to_column() %>%
    tidyr::pivot_longer(-rowname,names_to="ID",values_to="bin") %>%
    dplyr::mutate(bin = ifelse(is.na(bin), 0, 1))
  # Summarize the number of proteins identified
  # per sample and generate a barplot
  stat <- df %>%
    dplyr::group_by(ID) %>%
    dplyr::summarize(n = n(), sum = sum(bin)) %>%
    dplyr::left_join(., data.frame(colData(se)), by = "ID")
  total_proteins<-unique(stat$n)
  p <- ggplot(stat, aes(x = ID, y = sum, fill = condition)) +
    geom_col() +
    labs(title = "RBPs quantified per sample",
         x = "",
         y = "Number of proteins") +
    theme_RBP() + scale_RBP()
  if(plot) {
    return(p)
  } else {
    df <- as.data.frame(stat)
    colnames(df)[seq_len(3)] <- c("sample", "total_proteins", "proteins_in_sample")
    return(df)
  }
}
