#' test_onesample and volcano plot
#'
#' @param se SummarizedExperiment,
#' Data object for which to plot protein numbers
#'
#' @return Volcano plot of significant proteins
#' (generated by \code{\link[ggplot2]{ggplot}})
#' @import broom
#' @examples
#' if(interactive()){
#' test_onesample(data_filt)
#' }
#' @export
test_onesample <- function(se, plot=TRUE ){ #add volcano plot (plot=TRUE) or df (plot=FALSE)
  
  df<-as.data.frame(assay(se))
  ttest_sign <- vector("double",  dim(df)[1])
  minuslog10pvalue <- vector("double",  dim(df)[1])
  ttest_diff <- vector("double",  dim(df)[1])
  for( i in 1:dim(df)[1]){
    ttest_sign[[i]] <- t.test(df[i,1:6], mu = 0, alternative = "two.sided") %>%
      tidy() %>% pull(p.value)
    minuslog10pvalue[[i]] <-  t.test(df[i,1:6], mu = 0, alternative = "two.sided") %>%
      tidy() %>% pull(p.value) %>% log()/-1
    ttest_diff[[i]] <- mean(as.numeric(df[i,1:6] ),na.rm=TRUE)
  }
  df<-cbind(df,ttest_sign,minuslog10pvalue,ttest_diff)
  df$rownames<-df %>% rownames()
  p <- ggplot(df, aes(ttest_diff, minuslog10pvalue))+
    geom_point(aes(col = ttest_sign<0.05))+
    xlim(as.numeric(summary(df$ttest_diff)[2]*4),
         as.numeric(summary(df$ttest_diff)[5]*4))+
    ggrepel::geom_text_repel(data = filter(df, ttest_sign<0.05),
                             aes(label = rownames),  box.padding = unit(0.1,"lines"),
                             point.padding = unit(0.1, "lines"),segment.size = 0.5)+
    scale_RBP2()
  if(plot){
    return(p)
  }else{
    return(df)
  }
  
}


